server {
	listen 80;
	server_name _;
	auth_basic "Glassine git";
	auth_basic_user_file /etc/nginx/htpasswd;
	location / {
		client_max_body_size 50m;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /usr/libexec/git-core/git-http-backend;
		fastcgi_param GIT_HTTP_EXPORT_ALL "1";
		fastcgi_param GIT_PROJECT_ROOT /data/git;
		fastcgi_param PATH_INFO $uri;
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
	}
}
